/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.glavna;

import domain.Doktor;
import domain.Pacijent;
import domain.Pregled;
import domain.Racun;
import domain.Stavka;
import domain.Usluga;
import forme.FrmPregledi;
import forme.FrmPretraziIzmeniObrisiRacun;
import forme.FrmPretraziIzmeniPacijenta;
import forme.FrmUnosDoktora;
import forme.FrmUnosPacijenta;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import logika.KontrolerKlijent;
import modeli.StavkeTableModel;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Jovana
 */
public class FrmKlinika extends javax.swing.JFrame {

    //Doktor doktor;    
    Pacijent pacijent;
    static int brojac=0;
    double ukupanIznos;
    /**
     * Creates new form FrmKlinika
     */
    public FrmKlinika() {
        initComponents();
        setLocationRelativeTo(null);
        
        popuniCmbLista();
        
        tblStavke.setModel(new StavkeTableModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtUkupno = new javax.swing.JTextField();
        btnSacuvajRacun = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbPacijenti = new javax.swing.JComboBox();
        cmbDoktori = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUsluge = new javax.swing.JList();
        btnDodajStavku = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnIzmeniDoktora = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRacuni = new javax.swing.JMenu();
        miSviRacuni = new javax.swing.JMenuItem();
        miDodajPacijenta = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        miPretragaIzmenaPacijenta = new javax.swing.JMenuItem();
        menuDoktori = new javax.swing.JMenu();
        miDodajDoktora = new javax.swing.JMenuItem();
        jmiIzmeniDoktora = new javax.swing.JMenuItem();
        menuPregledi = new javax.swing.JMenu();
        jmiSviPregledi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStavke);

        jLabel6.setText("Ukupno:");

        btnSacuvajRacun.setText("Unesi racun");
        btnSacuvajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajRacunActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unesi pregled"));

        jLabel2.setText("Pacijent:");

        jLabel1.setText("Doktor:");

        cmbPacijenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPacijentiActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listUsluge);

        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        jLabel5.setText("Usluga:");

        btnIzmeniDoktora.setText("Izmeni doktora");
        btnIzmeniDoktora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniDoktoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDodajStavku))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIzmeniDoktora))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cmbDoktori, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDoktori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnIzmeniDoktora))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDodajStavku)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        menuRacuni.setText("Racuni");

        miSviRacuni.setText("Vidi sve racune");
        miSviRacuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSviRacuniActionPerformed(evt);
            }
        });
        menuRacuni.add(miSviRacuni);

        jMenuBar1.add(menuRacuni);

        miDodajPacijenta.setText("Pacijenti");

        jMenuItem2.setText("Unesi pacijenta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        miDodajPacijenta.add(jMenuItem2);

        miPretragaIzmenaPacijenta.setText("Pretrazi pacijenta");
        miPretragaIzmenaPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaIzmenaPacijentaActionPerformed(evt);
            }
        });
        miDodajPacijenta.add(miPretragaIzmenaPacijenta);

        jMenuBar1.add(miDodajPacijenta);

        menuDoktori.setText("Doktori");

        miDodajDoktora.setText("Unesi doktora");
        miDodajDoktora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDodajDoktoraActionPerformed(evt);
            }
        });
        menuDoktori.add(miDodajDoktora);

        jmiIzmeniDoktora.setText("Izmeni doktora");
        jmiIzmeniDoktora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzmeniDoktoraActionPerformed(evt);
            }
        });
        menuDoktori.add(jmiIzmeniDoktora);

        jMenuBar1.add(menuDoktori);

        menuPregledi.setText("Pregledi");
        menuPregledi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPreglediActionPerformed(evt);
            }
        });

        jmiSviPregledi.setText("Prikazi sve preglede");
        jmiSviPregledi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSviPreglediActionPerformed(evt);
            }
        });
        menuPregledi.add(jmiSviPregledi);

        jMenuBar1.add(menuPregledi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSacuvajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSacuvajRacun)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new FrmUnosPacijenta(null, this).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void miPretragaIzmenaPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaIzmenaPacijentaActionPerformed
        // TODO add your handling code here:
        new FrmPretraziIzmeniPacijenta().setVisible(true);
    }//GEN-LAST:event_miPretragaIzmenaPacijentaActionPerformed

    private void miDodajDoktoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDodajDoktoraActionPerformed
        // TODO add your handling code here:
        new FrmUnosDoktora(this,null).setVisible(true);
    }//GEN-LAST:event_miDodajDoktoraActionPerformed

    private void miSviRacuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSviRacuniActionPerformed
        // TODO add your handling code here:
        new FrmPretraziIzmeniObrisiRacun().setVisible(true);
    }//GEN-LAST:event_miSviRacuniActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        // TODO add your handling code here:
        try {
            
            StavkeTableModel ms=(StavkeTableModel) tblStavke.getModel();

           
            pacijent=(Pacijent) cmbPacijenti.getSelectedItem();
            
            Doktor doktor=(Doktor) cmbDoktori.getSelectedItem();

            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
            String datumVreme = sdf.format(new Date());

            Usluga usluga=(Usluga) listUsluge.getSelectedValue();
            Pregled pregled=new Pregled(0L, pacijent, doktor,usluga, sdf.parse(datumVreme));
            
            
            try {
                KontrolerKlijent.getInstance().sacuvajPregled(pregled);
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio pregled.");
            } catch (Exception exception) {
                JOptionPane.showMessageDialog(this, exception);
            }
            
            
            
            
//            racun=new Racun(0L, 0, pacijent);
//            KontrolerKlijent.getInstance().sacuvajRacun(racun);
//            
//            ArrayList<Racun> sacuvaniRacun=KontrolerKlijent.getInstance().vratiRacun(racun);
//            Racun racunBaza=sacuvaniRacun.get(0);
//            System.out.println(racunBaza.toString());
            
            Stavka stavka=new Stavka(0L, null,  pregled, usluga.getCena());
            
            ms.dodajStavku(stavka);
            ukupanIznos=0;
            
            for(Stavka st:ms.getListaStavki()){
                ukupanIznos+=st.getCena();
            }
            
            txtUkupno.setText(String.valueOf(ukupanIznos));
            
            
            brojac++;
            if(brojac>0){
                cmbPacijenti.setEnabled(false);
            }
            
            TableColumnModel columnModel=tblStavke.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(10);
            columnModel.getColumn(1).setPreferredWidth(200);
            columnModel.getColumn(2).setPreferredWidth(50);
            
            
        } catch (Exception e) {
            Logger.getLogger(FrmKlinika.class.getName()).log(Level.SEVERE,null,e);
        }
        
        
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnSacuvajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajRacunActionPerformed
        // TODO add your handling code here:
        try {
            StavkeTableModel ms=(StavkeTableModel) tblStavke.getModel();
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
            String datumVreme = sdf.format(new Date());
            Racun racun=new Racun(0L, ukupanIznos, pacijent,sdf.parse(datumVreme));
            
            racun.setLista(ms.getListaStavki());
            
            racun.setUkupanIznos(ukupanIznos);
            
            KontrolerKlijent.getInstance().sacuvajRacun(racun);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio racun.");
        } catch (Exception e) {
            Logger.getLogger(FrmKlinika.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_btnSacuvajRacunActionPerformed

    private void cmbPacijentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPacijentiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbPacijentiActionPerformed

    private void menuPreglediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPreglediActionPerformed
        
    }//GEN-LAST:event_menuPreglediActionPerformed

    private void jmiSviPreglediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSviPreglediActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            new FrmPregledi(this, true).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmKlinika.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiSviPreglediActionPerformed

    private void jmiIzmeniDoktoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzmeniDoktoraActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmiIzmeniDoktoraActionPerformed

    private void btnIzmeniDoktoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniDoktoraActionPerformed
        // TODO add your handling code here:
        
        Doktor doktor=(Doktor) cmbDoktori.getSelectedItem();
        new FrmUnosDoktora(this, doktor).setVisible(true);
        popuniCmbLista();
    }//GEN-LAST:event_btnIzmeniDoktoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKlinika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKlinika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKlinika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKlinika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmKlinika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzmeniDoktora;
    private javax.swing.JButton btnSacuvajRacun;
    private javax.swing.JComboBox cmbDoktori;
    private javax.swing.JComboBox cmbPacijenti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem jmiIzmeniDoktora;
    private javax.swing.JMenuItem jmiSviPregledi;
    private javax.swing.JList listUsluge;
    private javax.swing.JMenu menuDoktori;
    private javax.swing.JMenu menuPregledi;
    private javax.swing.JMenu menuRacuni;
    private javax.swing.JMenuItem miDodajDoktora;
    private javax.swing.JMenu miDodajPacijenta;
    private javax.swing.JMenuItem miPretragaIzmenaPacijenta;
    private javax.swing.JMenuItem miSviRacuni;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtUkupno;
    // End of variables declaration//GEN-END:variables

    public void popuniCmbLista() {
        try {
            cmbDoktori.removeAllItems();
            cmbPacijenti.removeAllItems();

            ArrayList<Pacijent> pacijenti=KontrolerKlijent.getInstance().vratiPacijente();
            ArrayList<Doktor> doktori= KontrolerKlijent.getInstance().vratiDoktore();
            ArrayList<Usluga> usluge=KontrolerKlijent.getInstance().vratiUsluge();

            DefaultListModel<Usluga> listModel=new DefaultListModel<>();
            listUsluge.setModel(listModel);
            for (Usluga usluga : usluge) {
                listModel.addElement(usluga);
            }

            for (Pacijent pacijent : pacijenti) {
                cmbPacijenti.addItem(pacijent);
            }
            for(Doktor doktor : doktori){
                cmbDoktori.addItem(doktor);
            }
            if(listModel.isEmpty()){
                JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita usluge!");
            }
            if(doktori.isEmpty()){
                JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita doktore!");
            }
            if(pacijenti.isEmpty()){
                JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita pacijente!");
            }
        } catch (Exception e) {
            Logger.getLogger(FrmKlinika.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }

    
}
